version: '2'

services:
        elasticsearch:
                build: elasticsearch
                ports:
                        - "9200:9200"
                        - "9300:9300"
                environment:
                        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
                networks:
                        - ServerMgmt
                        - IT
        logstash:
                build: logstash/
                command: -f /etc/logstash/conf.d/
                volumes:
                        - ./logstash/config:/etc/logstash/conf.d
                ports:
                        - "5000:5000"
                networks:
                        - ServerMgmt
        kibana:
                build: kibana/
                volumes:
                        - ./kibana/config/:/opt/kibana/config/
                ports:
                        - "5601:5601"
                networks:
                        - IT

networks:
        IT:
                driver: bridge
        ServerMgmt:
                driver: bridge
