version: '2'

services:
        elasticsearch:
                build: elasticsearch
                environment:
                        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
                networks:
                        KIBANA_ELASTIC:
                                ipv4_address: 192.168.120.2
                        LOGSTASH_ELASTIC:
                                ipv4_address: 192.168.120.10
        logstash:
                build: logstash/
                command: -f /etc/logstash/conf.d/
                volumes:
                        - ./logstash/config:/etc/logstash/conf.d
                ports:
                        - "${IFADDR_MGMT}:5000:5000"
                networks:
                        LOGSTASH_ELASTIC:
                                ipv4_address: 192.168.120.11
        kibana:
                build: kibana/
                volumes:
                        - ./kibana/config/:/opt/kibana/config/
                ports:
                        - "${IFADDR_IT}:5601:5601"
                networks:
                        KIBANA_ELASTIC:
                                ipv4_address: 192.168.120.3

networks:
        KIBANA_ELASTIC:
                driver: bridge
                ipam:
                        config:
                                - subnet: 192.168.120.0/29
        LOGSTASH_ELASTIC:
                driver: bridge
                ipam: 
                        config:
                                - subnet: 192.168.120.8/29

